apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blazormart-backend
  labels:
    app: blazormart-backend
spec:
  replicas: 1
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: blazormart-backend
        version: white
    spec:
      containers:
        - image: blazormart-server
          imagePullPolicy: IfNotPresent
          name: blazormart-backend
          ports:
            - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: blazormart-backend
  labels:
    app: blazormart-backend
spec:
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
  selector:
    app: blazormart-backend
